# Generated by Django 3.0.6 on 2020-06-01 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('sImg', models.ImageField(upload_to='boxes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Boxes',
            },
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(choices=[('Unknown publisher', 'Select a publisher'), ('Aspen Comics', 'Aspen Comics'), ('DC Comics', 'DC Comics'), ('Dark Horse', 'Dark Horse'), ('Image comics', 'Image comics'), ('Marvel', 'Marvel')], default='Make a selection', max_length=100)),
                ('name', models.CharField(max_length=120, verbose_name='Title')),
                ('slug', models.SlugField(unique=True)),
                ('sImg', models.ImageField(upload_to='comics/', verbose_name='Image')),
                ('number', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
                ('condition', models.CharField(choices=[('Unknown condition', 'Select a condition'), (10.0, 'Gem Mint (10)'), (9.9, 'Mint (9.9)'), (9.8, 'Near Mint / Mint (9.8)'), (9.6, 'Near Mint+ (9.6)'), (9.4, 'Near Mint (9.4)'), (9.2, 'Near Mint- (9.2)'), (9.0, 'Very Fine / Near Mint+ (9.0)'), (8.5, 'Very Fine+ (8.5)'), (8.0, 'Very Fine (8.0)'), (7.5, 'Very Fine- (7.5)'), (7.0, 'Fine / Very Fine (7.0)'), (6.5, 'Fine+ (6.5)'), (6.0, 'Fine (6.0)'), (5.5, 'Fine- (5.5)'), (5.0, 'Very Good / Fine (5.0)'), (4.5, 'Very Good+ (4.5)'), (4.0, 'Very Good (4.0)'), (3.5, 'Very Good- (3.5)'), (3.0, 'Good / Very Good+ (3.0)'), (2.5, 'Good+ (2.5)'), (2.0, 'Good (2.0)'), (1.8, 'Good- (1.8)'), (1.5, 'Fair / Good (1.5)'), (1.0, 'Fair (1.0)'), (0.5, 'Poor (0.5)')], default='Make a selection', max_length=100)),
                ('variant', models.CharField(max_length=5, verbose_name='Variant')),
                ('owned', models.BooleanField()),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comics', to='main.Box')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
