# Generated by Django 3.0.2 on 2020-04-09 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Box",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("sImg", models.ImageField(upload_to="boxes")),
            ],
            options={"verbose_name_plural": "Boxes",},
        ),
        migrations.CreateModel(
            name="Comic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        choices=[
                            ("PB", "Publisher"),
                            ("A", "Aspen Comics"),
                            ("DC", "DC Comics"),
                            ("DH", "Dark Horse"),
                            ("I", "Image comics"),
                            ("M", "Marvel"),
                        ],
                        default="PB",
                        max_length=2,
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Title")),
                ("sImg", models.ImageField(upload_to="comics/", verbose_name="Image")),
                ("number", models.PositiveSmallIntegerField()),
                ("date", models.DateField()),
                ("condition", models.CharField(max_length=5, verbose_name="Condition")),
                ("variant", models.CharField(max_length=5, verbose_name="Variant")),
                ("owned", models.BooleanField()),
                (
                    "box",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.Box"
                    ),
                ),
            ],
        ),
    ]
