NONE = "Make a selection"
PUBLISHER_CHOICES = [
    ("Unknown publisher", "Select a publisher"),
    ("Aspen Comics", "Aspen Comics"),
    ("DC Comics", "DC Comics"),
    ("Dark Horse", "Dark Horse"),
    ("Image comics", "Image comics"),
    ("Marvel", "Marvel"),
]

CONDITION_CHOICES = [
    ("Unknown condition", "Select a condition"),
    ("Condition: 10", "Gem Mint (10)"),
    ("Condition: 9.9", "Mint (9.9)"),
    ("Condition: 9.8", "Near Mint / Mint (9.8)"),
    ("Condition: 9.6", "Near Mint+ (9.6)"),
    ("Condition: 9.4", "Near Mint (9.4)"),
    ("Condition: 9.2", "Near Mint- (9.2)"),
    ("Condition: 9.0", "Very Fine / Near Mint+ (9.0)"),
    ("Condition: 8.5", "Very Fine+ (8.5)"),
    ("Condition: 8.0", "Very Fine (8.0)"),
    ("Condition: 7.5", "Very Fine- (7.5)"),
    ("Condition: 7.0", "Fine / Very Fine (7.0)"),
    ("Condition: 6.5", "Fine+ (6.5)"),
    ("Condition: 6.0", "Fine (6.0)"),
    ("Condition: 5.5", "Fine- (5.5)"),
    ("Condition: 5.0", "Very Good / Fine (5.0)"),
    ("Condition: 4.5", "Very Good+ (4.5)"),
    ("Condition: 4.0", "Very Good (4.0)"),
    ("Condition: 3.5", "Very Good- (3.5)"),
    ("Condition: 3.0", "Good / Very Good+ (3.0)"),
    ("Condition: 2.5", "Good+ (2.5)"),
    ("Condition: 2.0", "Good (2.0)"),
    ("Condition: 1.8", "Good- (1.8)"),
    ("Condition: 1.5", "Fair / Good (1.5)"),
    ("Condition: 1.0", "Fair (1.0)"),
    ("Condition: 0.5", "Poor (0.5)"),
]
